AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dynamodb-data-replication

  A Lambda script to replicate a database, backing it up in a DynamoDB table.
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 180
    Environment:
      Variables:
        TABLE_NAME: beer-test   # Your table name here
        TABLE_REGION: us-east-1 # Your table region here
        TABLE_UNIQUE_KEY_FIELD: id
        BASE_URL: https://kitsu.io/api/edge # replace with https://api.mlsgrid.com
        MLS_GRID_ACCESS_TOKEN: 123 # how should i define this value securely?

Resources:
  DataReplicationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: dist/
      Handler: app.lambdaHandler
      Events:
        DataReplication:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DataReplicationApi:
    Description: "API Gateway endpoint URL for Prod stage for Data Replication function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  DataReplicationFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt DataReplicationFunction.Arn
  DataReplicationFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt DataReplicationFunctionRole.Arn
