export interface MLSDataResponseInterface {
  '@odata.context': string;
  value: MLSDataValueInterface[];
  '@odata.nextLink'?: string;
}

export interface MLSDataValueInterface {
  id?: string;
  '@odata.id': string;
  'MFR_AdditionalRooms': string;
  'MFR_AlternateKeyFolioNum': string;
  'Appliances': string;
  'AssociationAmenities': string;
  'AssociationFee': number;
  'AssociationFeeFrequency': string;
  'MFR_AssociationFeeRequirement': string;
  'AssociationYN': boolean;
  'AttachedGarageYN': boolean;
  'MFR_AvailableForLeaseYN': string;
  'BathroomsFull': number;
  'BathroomsTotalInteger': number;
  'BedroomsTotal': number;
  'BuildingAreaSource': string;
  'BuildingAreaTotal': number;
  'MFR_BuildingElevatorYN': string;
  'MFR_BuildingNameNumber': string;
  'BuyerAgencyCompensation': string;
  'BuyerAgentAOR': string;
  'BuyerAgentFullName': string;
  'BuyerAgentMlsId': string;
  'BuyerOfficeMlsId': string;
  'BuyerOfficeName': string;
  'City': string;
  'CloseDate': string;
  'ClosePrice': number;
  'CoListAgentFullName': string;
  'CoListAgentMlsId': string;
  'CommunityFeatures': string;
  'MFR_ComplexCommunityNameNCCB': string;
  'ConstructionMaterials': string;
  'MFR_ContractStatus': string;
  'CountyOrParish': string;
  'CumulativeDaysOnMarket': number;
  'MFR_CurrentPrice': string;
  'DaysOnMarket': number;
  'MFR_DaysToClosed': string;
  'DirectionFaces': string;
  'Directions': string;
  'MFR_DPRURL': string;
  'MFR_DPRURL2': string;
  'MFR_DPRYN': string;
  'MFR_ExpectedClosingDate': string;
  'Flooring': string;
  'MFR_FloorNumber': string;
  'MFR_FutureLandUse': string;
  'GarageSpaces': number;
  'GarageYN': boolean;
  'MFR_HomesteadYN': string;
  'InteriorFeatures': string;
  'InternetAddressDisplayYN': boolean;
  'InternetEntireListingDisplayYN': boolean;
  'Latitude': number;
  'ListAgentAOR': string;
  'ListAgentDirectPhone': string;
  'ListAgentEmail': string;
  'ListAgentFax': string;
  'ListAgentFullName': string;
  'ListAgentKey': string;
  'ListAgentMlsId': string;
  'ListAgentOfficePhoneExt': string;
  'ListAgentPager': string;
  'ListAgentURL': string;
  'ListAOR': string;
  'ListingAgreement': string;
  'ListingContractDate': string;
  'ListingId': string;
  'ListingKey': string
  'OriginatingSystemKey': string;
  'ListOfficeFax': string;
  'MFR_ListOfficeHeadOfficeKeyNumeric': string;
  'ListOfficeKey': string;
  'ListOfficeMlsId': string
  'ListOfficeName': string
  'ListOfficePhone': string
  'ListPrice': number;
  'ListTeamName': string;
  'LivingArea': number;
  'Longitude': number;
  'LotSizeAcres': number;
  'LotSizeDimensions': string
  'MFR_MillageRate': string
  'MFR_MinimumLease': string
  'MLSAreaMajor': string
  'MlsStatus': string;
  'Model': string
  'OriginatingSystemModificationTimestamp': string
  'NewConstructionYN': boolean;
  'MFR_NonRepCompensation': string
  'MFR_NumTimesperYear': string
  'OffMarketDate': string
  'OriginalEntryTimestamp': string
  'OriginalListPrice': number;
  'OriginatingSystemName': string
  'MFR_OriginatingSystemTimestamp': string
  'ParcelNumber': string
  'PatioAndPorchFeatures': string
  'PetsAllowed': string
  'PhotosChangeTimestamp': string
  'PhotosCount': number;
  'PoolFeatures': string
  'PoolPrivateYN': boolean;
  'PostalCode': string;
  'PostalCodePlus4': string
  'PriceChangeTimestamp': string
  'PrivateRemarks': string
  'MFR_PropertyDescription': string
  'PropertySubType': string
  'PropertyType': string
  'PublicRemarks': string
  'PublicSurveyRange': string
  'PublicSurveySection': string
  'MFR_RoomCount': string;
  'ShowingRequirements': string
  'SpecialListingConditions': string
  'StandardStatus': string
  'StateOrProvince': string
  'StatusChangeTimestamp': string
  'StreetName': string
  'StreetNumber': string;
  'StreetSuffix': string
  'SubdivisionName': string
  'MFR_SubdivisionNum': string;
  'MFR_SWSubdivCommunityName': string
  'MFR_SWSubdivCondoNum': string
  'TaxAnnualAmount': number
  'TaxBlock': string
  'TaxBookNumber': string
  'TaxLegalDescription': string
  'TaxLot': string
  'TaxYear': number
  'MFR_TotalAcreage': string
  'Township': number
  'TransactionBrokerCompensation': number
  'UnitNumber': string
  'UnparsedAddress': string
  'Utilities': string
  'View': string
  'VirtualTourURLUnbranded': string
  'MFR_WaterAccess': string
  'MFR_WaterAccessYN': string
  'MFR_WaterExtrasYN': string
  'WaterfrontFeatures': string
  'WaterfrontYN': boolean;
  'MFR_WaterView': string
  'MFR_WaterViewYN': string
  'YearBuilt': number;
  'Zoning': string
  'MFR_ZoningCompatibleYN': string
  'RoomBedroom1Dimensions': string
  'RoomBedroom1Length': number;
  'RoomType': string
  'RoomBedroom1Width': number;
  'RoomKitchenDimensions': string
  'RoomKitchenLength': number;
  'RoomKitchenWidth': number;
  'RoomLivingRoomDimensions': string
  'RoomLivingRoomLength': number
  'RoomLivingRoomWidth': number;
  'RoomMasterBedroomDimensions': string
  'RoomMasterBedroomLength': number
  'RoomMasterBedroomWidth': number
  'RoomMasterBathroomFeatures': string
  'MlgCanView': boolean;
  'ModificationTimestamp': string
}